# Generated by Django 5.2.4 on 2025-07-31 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='account.accountmodel')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='account.accountmodel')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['from_account'], name='transaction_from_ac_6b2904_idx'), models.Index(fields=['to_account'], name='transaction_to_acco_6d95eb_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
    ]
